<?php

namespace AppBundle\Repository;

/**
 * LoadSchedulerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadSchedulerRepository extends \Doctrine\ORM\EntityRepository
{
}
