# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twig_php_extension:
        class: AppBundle\Twig\PhpExtension
        tags:
            - { name: twig.extension }
    app.text_modifier:
        class: AppBundle\Service\TextModifier
    app.loan_calculator:
        class: AppBundle\Service\LoanCalculator
